
server {
    server_name partners.hubicx.ru;
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    server_name partners.hubicx.ru;

    root /opt/ai_aggregator/webapp/public/partners;

    location /app/assets/ {
        root /opt/ai_aggregator/webapp/public;
    }

    location / {
        try_files $uri /index.html;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/api.hubicx.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.hubicx.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
