AI_MODELS_CATALOG = [
    {
        "code": "nano_banana",
        "title": "Nano Banana",
        "category": "photo",
        "provider": "fal",
        "provider_model_id": "placeholder/nano-banana",
        "task_type": "image",
        "input_type": "text_image",
        "price_credits": 30,
        "is_active": True,
        "sort_order": 10,
        "default_params": {"image_size": "square_hd", "num_inference_steps": 4},
        "description": "Быстрая image-generation модель. Для production укажите реальный Fal model id.",
    },
    {
        "code": "gpt_image_2",
        "title": "GPT Image 2",
        "category": "photo",
        "provider": "openrouter",
        "provider_model_id": "placeholder/gpt-image-2",
        "task_type": "image",
        "input_type": "text_image",
        "price_credits": 40,
        "is_active": True,
        "sort_order": 20,
        "default_params": {"quality": "standard"},
        "description": "Генерация и редактирование изображений через image-capable провайдера.",
    },
    {
        "code": "seedream",
        "title": "Seedream",
        "category": "photo",
        "provider": "fal",
        "provider_model_id": "placeholder/seedream",
        "task_type": "image",
        "input_type": "text_image",
        "price_credits": 35,
        "is_active": True,
        "sort_order": 30,
        "default_params": {"image_size": "square_hd"},
        "description": "Image модель для фотореалистичных генераций и edits.",
    },
    {
        "code": "grok_image",
        "title": "Grok",
        "category": "photo",
        "provider": "openrouter",
        "provider_model_id": "placeholder/grok-image",
        "task_type": "image",
        "input_type": "text",
        "price_credits": 35,
        "is_active": True,
        "sort_order": 40,
        "default_params": {},
        "description": "Image модель семейства Grok, включается после настройки provider_model_id.",
    },
    {
        "code": "z_image",
        "title": "Z-Image",
        "category": "photo",
        "provider": "fal",
        "provider_model_id": "placeholder/z-image",
        "task_type": "image",
        "input_type": "text",
        "price_credits": 25,
        "is_active": True,
        "sort_order": 50,
        "default_params": {"image_size": "square_hd"},
        "description": "Доступная текст-в-изображение модель для быстрых генераций.",
    },
    {
        "code": "seedance",
        "title": "Seedance",
        "category": "video",
        "provider": "fal",
        "provider_model_id": "placeholder/seedance",
        "task_type": "video",
        "input_type": "text_image",
        "price_credits": 80,
        "is_active": True,
        "sort_order": 10,
        "default_params": {"duration": 5},
        "description": "Video модель для text/image-to-video сценариев.",
    },
    {
        "code": "veo",
        "title": "VEO",
        "category": "video",
        "provider": "fal",
        "provider_model_id": "placeholder/veo",
        "task_type": "video",
        "input_type": "text_image",
        "price_credits": 120,
        "is_active": True,
        "sort_order": 20,
        "default_params": {"duration": 5},
        "description": "Премиальная video модель, требует реальный provider_model_id.",
    },
    {
        "code": "kling",
        "title": "Kling",
        "category": "video",
        "provider": "fal",
        "provider_model_id": "placeholder/kling",
        "task_type": "video",
        "input_type": "text_image",
        "price_credits": 90,
        "is_active": True,
        "sort_order": 30,
        "default_params": {"duration": 5},
        "description": "Video модель Kling для кинематографичных роликов.",
    },
    {
        "code": "grok_video",
        "title": "Grok",
        "category": "video",
        "provider": "fal",
        "provider_model_id": "placeholder/grok-video",
        "task_type": "video",
        "input_type": "text",
        "price_credits": 100,
        "is_active": True,
        "sort_order": 40,
        "default_params": {"duration": 5},
        "description": "Video модель Grok, безопасно выключена placeholder id до настройки.",
    },
    {
        "code": "happyhorse",
        "title": "HappyHorse 1.0",
        "category": "video",
        "provider": "fal",
        "provider_model_id": "placeholder/happyhorse",
        "task_type": "video",
        "input_type": "text_image",
        "price_credits": 70,
        "is_active": True,
        "sort_order": 50,
        "default_params": {"duration": 5},
        "description": "Экспериментальная video модель для image-to-video сценариев.",
    },
    {
        "code": "gemini_omni",
        "title": "Gemini Omni",
        "category": "video",
        "provider": "fal",
        "provider_model_id": "placeholder/gemini-omni",
        "task_type": "video",
        "input_type": "text_image",
        "price_credits": 100,
        "is_active": True,
        "sort_order": 60,
        "default_params": {"duration": 5},
        "description": "Мультимодальная video модель, включается после настройки provider_model_id.",
    },
    {
        "code": "ai_chat",
        "title": "Чат с ИИ",
        "category": "text",
        "provider": "openrouter",
        "provider_model_id": "openai/gpt-4o-mini",
        "task_type": "text",
        "input_type": "text",
        "price_credits": 2,
        "is_active": True,
        "sort_order": 10,
        "default_params": {"max_tokens": 800, "temperature": 0.7},
        "description": "Текстовый чат через OpenRouter, готов к production при наличии OPENROUTER_API_KEY.",
    },
    {
        "code": "prompt_helper",
        "title": "Помощник промптов",
        "category": "text",
        "provider": "openrouter",
        "provider_model_id": "openai/gpt-4o-mini",
        "task_type": "text",
        "input_type": "text",
        "price_credits": 2,
        "is_active": True,
        "sort_order": 20,
        "default_params": {"max_tokens": 1000, "temperature": 0.5},
        "description": "Улучшает пользовательские промпты для генеративных моделей.",
    },
    {
        "code": "voice_transcription",
        "title": "Расшифровка голосовых",
        "category": "text",
        "provider": "openrouter",
        "provider_model_id": "placeholder/voice-transcription",
        "task_type": "audio",
        "input_type": "audio",
        "price_credits": 10,
        "is_active": True,
        "sort_order": 30,
        "default_params": {},
        "description": "Audio transcription модель, требует отдельный provider_model_id перед включением.",
    },
]
