/* ============ Hubicx i18n ru/en/es/pt ============ */
(function(){
  const LANGS = ['ru','en','es','pt'];
  const D = {
    ru: {
      'nav.agent':'Агент','nav.generation':'Генерация','nav.profile':'Профиль',
      'common.buy_pro':'Купить Hubicx Pro','common.balance_unavailable':'Баланс временно недоступен','common.open_telegram':'Откройте приложение через Telegram','common.retry':'Повторите попытку','common.save':'Сохранить','common.cancel':'Отмена','common.close':'Закрыть','common.open':'Открыть','common.copy':'Скопировать','common.copied':'Скопировано','common.copy_failed':'Не удалось скопировать','common.show_all':'Показать все','common.tokens':'токенов','common.cost':'Стоимость','common.status':'Статус','common.date':'Дата','common.task':'Задача','common.error':'Ошибка','common.ready':'Готово','common.processing':'В процессе','common.refresh':'Обновить','common.choose':'Выберите',
      'agent.title':'Чем я могу помочь Вам сегодня?','agent.placeholder':'Спросить что-нибудь...','agent.create_photo':'Создать фото','agent.create_video':'Создать видео','agent.add_chat':'Добавить в чат','agent.my_chats':'Мои чаты','agent.media':'Фото и видео','agent.hubicx_agent':'Агент Hubicx','agent.typing':'печатает…','agent.online':'онлайн','agent.message':'Сообщение...','agent.no_answer':'Не удалось получить ответ','agent.new_chat':'Новый чат',
      'agent.prompt_master.desc':'Улучшает промпты для фото, видео и текста','agent.smm.desc':'Идеи, посты и контент-планы','agent.brief.desc':'Собирает понятный дизайн-бриф','agent.video.desc':'Сценарии и shot list для видео','agent.botcopy.desc':'Тексты для Telegram-ботов',
      'agent.mode.general':'Обычный чат','agent.mode.general.desc':'Универсальный помощник без узкой роли','agent.mode.prompt_master':'Prompt Master','agent.mode.prompt_master.desc':'Улучшает промпты для фото, видео и текста','agent.mode.smm_assistant':'SMM Assistant','agent.mode.smm_assistant.desc':'Помогает с постами, контентом и прогревами','agent.mode.design_brief':'Design Brief Builder','agent.mode.design_brief.desc':'Собирает понятное ТЗ для дизайна','agent.mode.video_script':'Video Script Writer','agent.mode.video_script.desc':'Помогает писать сценарии и раскадровки','agent.mode.bot_copywriter':'Telegram Bot Copywriter','agent.mode.bot_copywriter.desc':'Пишет тексты для ботов, кнопок и сообщений',
      'chat.mode':'Режим','chat.choose_mode':'Выберите режим чата','chat.quick.help':'Помоги разобраться','chat.quick.plan':'Составь план','chat.quick.short':'Сделай кратко',
      'quick.improve':'Улучши промпт','quick.variants':'Сделай 3 варианта','quick.cinematic':'Добавь cinematic стиль','quick.tg_post':'Пост для Telegram','quick.reels':'Идеи Reels','quick.week_plan':'Контент-план на неделю','quick.brief':'Собери бриф','quick.moodboard':'Moodboard prompt','quick.brand':'Опиши стиль бренда','quick.script15':'Сценарий 15 сек','quick.shotlist':'Shot list','quick.hook':'Hook для рекламы','quick.onboarding':'Онбординг','quick.buttons':'Текст кнопок','quick.payment':'Сообщение после оплаты',
      'gen.photo_video':'Фото и видео','gen.photo':'Фото','gen.video':'Видео','gen.templates':'Шаблоны','gen.create_photo':'Создать фото','gen.create_video':'Создать видео','gen.my_tokens':'мои токены','gen.topup':'Пополнить','gen.balance':'баланс','gen.upload_photo':'Загрузить селфи или фото','gen.upload_video':'Загрузить фото для видео','gen.choose_tpl':'Выбрать шаблон','gen.custom_prompt':'Свой промпт','gen.prompt_ph':'Опишите, что хотите сгенерировать...','gen.details':'Детали','gen.model':'Модель','gen.aspect':'Соотношение сторон','gen.select_model':'Выберите модель','gen.select_tpl':'Выберите шаблон','gen.enter_prompt':'Укажите промпт','gen.create':'Создать','gen.creating':'Создаю…','gen.with_audio':'Со звуком','gen.no_audio':'Без звука','gen.one_image':'1 изображение','gen.seconds':'сек','gen.price_unavailable':'Цена недоступна','gen.file_uploading':'Загружаю файл…','gen.file_uploaded':'Файл загружен','gen.file_failed':'Не удалось загрузить файл','gen.need_image':'Для этой модели нужно загрузить изображение','gen.need_photo_model':'Выберите фото-модель','gen.need_video_model':'Выберите видео-модель','gen.task_created':'Задача создана, ожидаю результат…','gen.task_status':'Статус: {status}','gen.long_task':'Задача ещё выполняется. Результат появится в истории.','gen.create_failed':'Не удалось создать генерацию','gen.generation_failed':'Генерация завершилась ошибкой',
      'result.ready':'Результат готов','result.failed':'Ошибка генерации','result.refunded':'Средства возвращены','result.processing':'Генерация выполняется','result.open':'Открыть','result.send_tg':'Отправить в Telegram','result.new':'Новая генерация','result.copy':'Скопировать','result.continue_chat':'Продолжить в чате','result.sending':'Отправляю в Telegram…','result.sent':'Отправлено в Telegram','result.send_failed':'Не удалось отправить в Telegram','result.unavailable':'Результат пока недоступен',
      'history.title':'Последние результаты','history.empty':'История появится после генераций.','history.failed':'Ошибка генерации','history.status_ready':'готово','history.status_error':'ошибка','history.status_refunded':'возврат','history.status_processing':'выполняется','history.status_queued':'в очереди','history.status':'статус','history.unavailable':'История временно недоступна',
      'profile.title':'Профиль','profile.loaded':'Настройки загружены','profile.saved':'Настройки сохранены','profile.local':'Профиль временно доступен локально','profile.telegram_save':'Откройте через Telegram для сохранения настроек','profile.tokens':'Мои токены','profile.llm':'LLM-модель','profile.language':'Язык','profile.daily':'Hubicx Daily','profile.on':'Включен','profile.off':'Выключен','profile.personality':'Личность Hubicx','profile.about':'О Вас','profile.style':'Стиль общения','profile.set_style':'Указать стиль общения','profile.hubicx_lang':'Язык Hubicx','profile.set_hubicx_lang':'Указать язык Hubicx','profile.emoji':'Любимый эмодзи','profile.traits':'Черты характера','profile.set_traits':'Указать черты характера','profile.traits_ph':'Например: спокойный, внимательный...','profile.name':'Имя','profile.set_name':'Указать имя','profile.name_ph':'Ваше имя','profile.gender':'Пол','profile.set_gender':'Указать пол','profile.age':'Возраст','profile.set_age':'Указать возраст','profile.location':'Локация','profile.set_location':'Указать локацию','profile.location_ph':'Город','profile.activity':'Вид деятельности','profile.set_activity':'Указать вид деятельности','profile.activity_ph':'Чем вы занимаетесь','profile.interests':'Интересы','profile.set_interests':'Указать интересы','profile.interests_ph':'Ваши интересы','profile.timezone':'Часовой пояс','profile.set_timezone':'Указать часовой пояс','profile.value_ph':'Введите значение',      'profile.topup':'Пополнить токены','profile.current_balance':'Текущий баланс: {tokens}','profile.pay':'Оплатить {price}','profile.good_deal':'Выгодно',
      'doc.title':'Документы','doc.support':'Поддержка','doc.terms':'Пользовательское соглашение','doc.privacy':'Политика конфиденциальности','doc.payment':'Правила оплаты','doc.refund':'Правила возврата токенов','doc.how_tokens':'Как работают токены',
      'topup.yookassa_note':'Оплата через ЮKassa скоро будет доступна. Сейчас пополнение возможно через администратора.',
      'model.image_fast':'Фото · быстро','model.image_pro':'Фото · Pro','model.image_edit':'Фото · редактирование','model.image_real':'Фото · реализм','model.image_turbo':'Фото · turbo','model.video_t2v':'Видео · текст в видео','model.video_i2v_fast':'Видео · быстрое оживление','model.video_i2v':'Видео · качественное оживление','model.video_kling':'Видео · image-to-video','model.text_chat':'Текст · чат','model.text_prompt':'Текст · промпты','aspect.square':'Квадрат','aspect.portrait':'Портрет','aspect.album':'Альбом','aspect.stories':'Сторис','aspect.wide':'Широкий'
    },
    en: {
      'nav.agent':'Agent','nav.generation':'Generation','nav.profile':'Profile','common.buy_pro':'Buy Hubicx Pro','common.balance_unavailable':'Balance temporarily unavailable','common.open_telegram':'Open the app in Telegram','common.retry':'Try again','common.save':'Save','common.cancel':'Cancel','common.close':'Close','common.open':'Open','common.copy':'Copy','common.copied':'Copied','common.copy_failed':'Could not copy','common.show_all':'Show all','common.tokens':'tokens','common.cost':'Cost','common.status':'Status','common.date':'Date','common.task':'Task','common.error':'Error','common.ready':'Done','common.processing':'Processing','common.refresh':'Refresh','common.choose':'Choose',
      'agent.title':'How can I help you today?','agent.placeholder':'Ask anything...','agent.create_photo':'Create photo','agent.create_video':'Create video','agent.add_chat':'Add to chat','agent.my_chats':'My chats','agent.media':'Photo and video','agent.hubicx_agent':'Hubicx Agent','agent.typing':'typing…','agent.online':'online','agent.message':'Message...','agent.no_answer':'Could not get a response','agent.new_chat':'New chat','agent.prompt_master.desc':'Improves prompts for images, video and text','agent.smm.desc':'Ideas, posts and content plans','agent.brief.desc':'Builds a clear design brief','agent.video.desc':'Scripts and shot lists for video','agent.botcopy.desc':'Copy for Telegram bots',
      'quick.improve':'Improve prompt','quick.variants':'Make 3 variants','quick.cinematic':'Add cinematic style','quick.tg_post':'Telegram post','quick.reels':'Reels ideas','quick.week_plan':'Weekly content plan','quick.brief':'Build a brief','quick.moodboard':'Moodboard prompt','quick.brand':'Describe brand style','quick.script15':'15 sec script','quick.shotlist':'Shot list','quick.hook':'Ad hook','quick.onboarding':'Onboarding','quick.buttons':'Button text','quick.payment':'After-payment message',
      'agent.mode.general':'General chat','agent.mode.general.desc':'Universal assistant without a specific role','agent.mode.prompt_master':'Prompt Master','agent.mode.prompt_master.desc':'Improves prompts for images, video and text','agent.mode.smm_assistant':'SMM Assistant','agent.mode.smm_assistant.desc':'Helps with posts, content and engagement','agent.mode.design_brief':'Design Brief Builder','agent.mode.design_brief.desc':'Builds a clear design brief','agent.mode.video_script':'Video Script Writer','agent.mode.video_script.desc':'Helps write scripts and storyboards','agent.mode.bot_copywriter':'Telegram Bot Copywriter','agent.mode.bot_copywriter.desc':'Writes copy for bots, buttons and messages',
      'chat.mode':'Mode','chat.choose_mode':'Choose chat mode','chat.quick.help':'Help me figure it out','chat.quick.plan':'Make a plan','chat.quick.short':'Keep it short',
      'gen.photo_video':'Photo and video','gen.photo':'Photo','gen.video':'Video','gen.templates':'Templates','gen.create_photo':'Create photo','gen.create_video':'Create video','gen.my_tokens':'my tokens','gen.topup':'Top up','gen.balance':'balance','gen.upload_photo':'Upload selfie or photo','gen.upload_video':'Upload photo for video','gen.choose_tpl':'Choose template','gen.custom_prompt':'Custom prompt','gen.prompt_ph':'Describe what you want to generate...','gen.details':'Details','gen.model':'Model','gen.aspect':'Aspect ratio','gen.select_model':'Choose model','gen.select_tpl':'Choose template','gen.enter_prompt':'Enter prompt','gen.create':'Create','gen.creating':'Creating…','gen.with_audio':'With audio','gen.no_audio':'No audio','gen.one_image':'1 image','gen.seconds':'sec','gen.price_unavailable':'Price unavailable','gen.file_uploading':'Uploading file…','gen.file_uploaded':'File uploaded','gen.file_failed':'Could not upload file','gen.need_image':'This model requires an image','gen.need_photo_model':'Choose an image model','gen.need_video_model':'Choose a video model','gen.task_created':'Task created, waiting for result…','gen.task_status':'Status: {status}','gen.long_task':'Task is still running. The result will appear in history.','gen.create_failed':'Could not create generation','gen.generation_failed':'Generation failed',
      'result.ready':'Result ready','result.failed':'Generation error','result.refunded':'Credits refunded','result.processing':'Generation in progress','result.open':'Open','result.send_tg':'Send to Telegram','result.new':'New generation','result.copy':'Copy','result.continue_chat':'Continue in chat','result.sending':'Sending to Telegram…','result.sent':'Sent to Telegram','result.send_failed':'Could not send to Telegram','result.unavailable':'Result is not available yet',
      'history.title':'Recent results','history.empty':'History will appear after generations.','history.failed':'Generation error','history.status_ready':'done','history.status_error':'error','history.status_refunded':'refunded','history.status_processing':'processing','history.status_queued':'queued','history.status':'status','history.unavailable':'History temporarily unavailable',
      'profile.title':'Profile','profile.loaded':'Settings loaded','profile.saved':'Settings saved','profile.local':'Profile is temporarily local','profile.telegram_save':'Open in Telegram to save settings','profile.tokens':'My tokens','profile.llm':'LLM model','profile.language':'Language','profile.daily':'Hubicx Daily','profile.on':'On','profile.off':'Off','profile.personality':'Hubicx personality','profile.about':'About you','profile.style':'Communication style','profile.set_style':'Set communication style','profile.hubicx_lang':'Hubicx language','profile.set_hubicx_lang':'Set Hubicx language','profile.emoji':'Favorite emoji','profile.traits':'Traits','profile.set_traits':'Set traits','profile.traits_ph':'For example: calm, attentive...','profile.name':'Name','profile.set_name':'Set name','profile.name_ph':'Your name','profile.gender':'Gender','profile.set_gender':'Set gender','profile.age':'Age','profile.set_age':'Set age','profile.location':'Location','profile.set_location':'Set location','profile.location_ph':'City','profile.activity':'Activity','profile.set_activity':'Set activity','profile.activity_ph':'What you do','profile.interests':'Interests','profile.set_interests':'Set interests','profile.interests_ph':'Your interests','profile.timezone':'Timezone','profile.set_timezone':'Set timezone','profile.value_ph':'Enter value',      'profile.topup':'Top up tokens','profile.current_balance':'Current balance: {tokens}','profile.pay':'Pay {price}','profile.good_deal':'Best value',
      'doc.title':'Documents','doc.support':'Support','doc.terms':'Terms of Service','doc.privacy':'Privacy Policy','doc.payment':'Payment Rules','doc.refund':'Token Refund Policy','doc.how_tokens':'How Tokens Work',
      'topup.yookassa_note':'Payment via YooKassa coming soon. Currently, top-up is available through the administrator.',
      'model.image_fast':'Image · fast','model.image_pro':'Image · Pro','model.image_edit':'Image · editing','model.image_real':'Image · realism','model.image_turbo':'Image · turbo','model.video_t2v':'Video · text to video','model.video_i2v_fast':'Video · fast animation','model.video_i2v':'Video · quality animation','model.video_kling':'Video · image-to-video','model.text_chat':'Text · chat','model.text_prompt':'Text · prompts','aspect.square':'Square','aspect.portrait':'Portrait','aspect.album':'Landscape','aspect.stories':'Stories','aspect.wide':'Wide'
    },
    es: {}, pt: {}
  };
  D.es = {...D.en, 'nav.agent':'Agente','nav.generation':'Generación','nav.profile':'Perfil','common.save':'Guardar','common.close':'Cerrar','common.open':'Abrir','common.copy':'Copiar','common.refresh':'Actualizar','common.open_telegram':'Abre la app en Telegram','agent.title':'¿Cómo puedo ayudarte hoy?','agent.placeholder':'Pregunta algo...','agent.create_photo':'Crear foto','agent.create_video':'Crear vídeo','agent.add_chat':'Añadir al chat','agent.my_chats':'Mis chats','agent.media':'Foto y vídeo','agent.typing':'escribiendo…','agent.online':'en línea','agent.message':'Mensaje...','agent.mode.general':'Chat general','agent.mode.general.desc':'Asistente universal sin rol específico','chat.mode':'Modo','chat.choose_mode':'Elige modo de chat','chat.quick.help':'Ayúdame a entender','chat.quick.plan':'Haz un plan','chat.quick.short':'Sé breve','gen.photo':'Foto','gen.video':'Vídeo','gen.templates':'Plantillas','gen.create_photo':'Crear foto','gen.create_video':'Crear vídeo','gen.topup':'Recargar','gen.model':'Modelo','gen.aspect':'Relación de aspecto','gen.create':'Crear','result.ready':'Resultado listo','result.send_tg':'Enviar a Telegram','result.new':'Nueva generación','result.continue_chat':'Continuar en chat','history.title':'Resultados recientes','history.empty':'El historial aparecerá después de las generaciones.','profile.title':'Perfil','profile.tokens':'Mis tokens','profile.language':'Idioma','profile.daily':'Hubicx Daily','profile.on':'Activado','profile.off':'Desactivado','profile.personality':'Personalidad Hubicx','profile.about':'Sobre ti','profile.style':'Estilo de comunicación','profile.saved':'Ajustes guardados','profile.loaded':'Ajustes cargados','doc.title':'Documentos','doc.support':'Soporte','doc.terms':'Términos de servicio','doc.privacy':'Política de privacidad','doc.payment':'Reglas de pago','doc.refund':'Reglas de devolución','doc.how_tokens':'Cómo funcionan los tokens','topup.yookassa_note':'Pago a través de YooKassa próximamente. Actualmente, la recarga está disponible a través del administrador.'};
  D.pt = {...D.en, 'nav.agent':'Agente','nav.generation':'Geração','nav.profile':'Perfil','common.save':'Salvar','common.close':'Fechar','common.open':'Abrir','common.copy':'Copiar','common.refresh':'Atualizar','common.open_telegram':'Abra o app no Telegram','agent.title':'Como posso ajudar você hoje?','agent.placeholder':'Pergunte algo...','agent.create_photo':'Criar foto','agent.create_video':'Criar vídeo','agent.add_chat':'Adicionar ao chat','agent.my_chats':'Meus chats','agent.media':'Foto e vídeo','agent.typing':'digitando…','agent.online':'online','agent.message':'Mensagem...','agent.mode.general':'Chat geral','agent.mode.general.desc':'Assistente universal sem papel específico','chat.mode':'Modo','chat.choose_mode':'Escolha modo do chat','chat.quick.help':'Me ajude a entender','chat.quick.plan':'Faça um plano','chat.quick.short':'Seja breve','gen.photo':'Foto','gen.video':'Vídeo','gen.templates':'Modelos','gen.create_photo':'Criar foto','gen.create_video':'Criar vídeo','gen.topup':'Recarregar','gen.model':'Modelo','gen.aspect':'Proporção','gen.create':'Criar','result.ready':'Resultado pronto','result.send_tg':'Enviar ao Telegram','result.new':'Nova geração','result.continue_chat':'Continuar no chat','history.title':'Resultados recentes','history.empty':'O histórico aparecerá após as gerações.','profile.title':'Perfil','profile.tokens':'Meus tokens','profile.language':'Idioma','profile.daily':'Hubicx Daily','profile.on':'Ativado','profile.off':'Desativado','profile.personality':'Personalidade Hubicx','profile.about':'Sobre você','profile.style':'Estilo de comunicação','profile.saved':'Configurações salvas','profile.loaded':'Configurações carregadas','doc.title':'Documentos','doc.support':'Suporte','doc.terms':'Termos de serviço','doc.privacy':'Política de privacidade','doc.payment':'Regras de pagamento','doc.refund':'Regras de reembolso','doc.how_tokens':'Como funcionam os tokens','topup.yookassa_note':'Pagamento via YooKassa em breve. Atualmente, a recarga está disponível através do administrador.'};
  function norm(lang){ lang=String(lang||'').slice(0,2).toLowerCase(); return LANGS.includes(lang) ? lang : 'ru'; }
  function detect(){
    try{ const p=JSON.parse(localStorage.getItem('hbx_profile_v1')||localStorage.getItem('hubicx-profile')||'{}'); if(p.language_code||p.lang) return norm(p.language_code||p.lang); }catch(e){}
    try{ const s=localStorage.getItem('hubicx-locale')||localStorage.getItem('hbx_lang')||localStorage.getItem('hubicx-language'); if(s) return norm(s); }catch(e){}
    try{ const tg=window.Telegram&&window.Telegram.WebApp; const lc=tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user&&tg.initDataUnsafe.user.language_code; if(lc) return norm(lc); }catch(e){}
    return 'ru';
  }
  let current = detect();
  function tr(key, params){
    let out = (D[current]&&D[current][key]) || D.ru[key] || key;
    if(params) Object.keys(params).forEach(k=>{ out = out.replace(new RegExp('\\{'+k+'\\}','g'), params[k]); });
    return out;
  }
  function setLang(lang){
    current = norm(lang);
    try{ localStorage.setItem('hubicx-locale', current); localStorage.setItem('hbx_lang', current); localStorage.setItem('hubicx-language', current); document.documentElement.lang=current; }catch(e){}
    window.dispatchEvent(new CustomEvent('hubicx:lang',{detail:{lang:current}}));
    return current;
  }
  window.HubicxI18n = { dictionaries:D, languages:LANGS, norm, detect, getLang:()=>current, setLang, t:tr };
  window.t = tr;
  try{ document.documentElement.lang=current; }catch(e){}
})();
